### ISSUE TITLE
Can't apply executable permission to globalify.sh script

### ISSUE THREAD

**Issue by rbeesley** [filiphsandstrom/surface-duo#2]
I know you closed #1, but the problem still remains. As root using su, you can't use `chmod +x globalify.sh` and make it so that you can execute the script. This will prevent anyone from successfully flashing their device if they only follow the guide and don't have deeper knowledge about what these commands are doing.

**Comment by kenpc-git** [comment]
I made a PR on the readme that solves this.

> I know you closed #1, but the problem still remains. As root using su, you can't use `chmod +x globalify.sh` and make it so that you can execute the script. This will prevent anyone from successfully flashing their device if they only follow the guide and don't have deeper knowledge about what these commands are doing.
